name: Python application

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Lint with black, flake8 and mypy
      run: |
        poetry run black --check .
        poetry run flake8 .
        poetry run mypy .
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Build with poetry
      run: |
        poetry build
    - name: Upload distribution
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish to PyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: publishing
      url: https://pypi.org/p/buva-qstream
    permissions:
      id-token: write
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
